In [3]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
plt.style.use("fivethirtyeight")

In [2]:
!pip install joblib

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 1.6 MB/s eta 0:00:00m eta 0:00:010:00:01


In [18]:
# create a perceptron class

class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        # np.c_ means concatenation operation
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias value:\n {X_with_bias}")
        

In [19]:
obj = Perceptron()

In [20]:
eta = 0.01
epochs = 10

In [21]:
obj = Perceptron(eta, epochs)

In [22]:
obj.eta

0.01

In [23]:
obj.epochs

10

In [24]:
X = np.ones((4,2))

In [25]:
y = np.ones((4,1))

In [26]:
obj.fit(X, y)

X with bias value:
 [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
