In [37]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
plt.style.use("fivethirtyeight")
import pandas as pd

In [38]:
!pip install joblib

In [61]:
# create a perceptron class

class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1 , 0)
    
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        # np.c_ means concatenation operation
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias value:\n {X_with_bias}")
        
        for epoch in range(self.epochs):
            print('---'*10)
            print(f"for epoch >> {epoch+1}")
            print('---'*10)
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after the forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch :{epoch + 1}: \n {self.weights} ")
    
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
# when training forward and backward pass both needed
# when prediction then only forward pass is needed
        

In [62]:
OR = {
    'x1': [0,0,1,1],
    'x2': [0,1,0,1],
    'y': [0,1,1,1]
}

df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [63]:
def prepare_data(df, target_col = 'y'):
    X = df.drop(target_col, axis = 1)
    y = df[target_col]
    return X,y

In [64]:
X, y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA, epochs = EPOCHS)

In [65]:
model_or.fit(X,y)

X with bias value:
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
------------------------------
for epoch >> 1
------------------------------
predicted value after the forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch :1: 
 [ 0.19993795  0.20004297 -0.29980947] 
------------------------------
for epoch >> 2
------------------------------
predicted value after the forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch :2: 
 [ 0.19993795  0.20004297 -0.19980947] 
------------------------------
for epoch >> 3
------------------------------
predicted value after the forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch :3: 
 [ 0.19993795  0.20004297 -0.09980947] 
------------------------------
for epoch >> 4
------------------------------
predicted value after the forward pass: 
[1 1 1 1]
error: 
0   -1

In [66]:
model_or.predict(X)

array([0, 1, 1, 1])